export const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS';
export const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS';
export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const CHANGE_CHARACTER = 'CHANGE_CHARACTER';
